# Generated by Django 5.2.1 on 2025-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_alter_question_author_alter_question_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="category_type",
            field=models.CharField(
                choices=[("major", "대분류"), ("middle", "중분류"), ("minor", "소분류"), ("general", "일반질문")],
                default="general",
                max_length=10,
            ),
        ),
    ]
