# Generated by Django 5.2.1 on 2025-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="thumbnail_img_url",
            field=models.URLField(),
        ),
    ]
