# Generated by Django 5.2.1 on 2025-07-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_subject_thumbnail_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="status",
            field=models.CharField(
                choices=[("Ready", "시작 전"), ("Ongoing", "진행 중"), ("Finished", "종료")],
                default="Ready",
                max_length=10,
            ),
        ),
    ]
