# Generated by Django 5.2.1 on 2025-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_generation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="generation",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
