# Generated by Django 5.2.1 on 2025-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("profile_image_url", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "어드민"),
                            ("GENERAL", "일반회원"),
                            ("STUDENT", "수강생"),
                            ("TA", "조교"),
                            ("OM", "운영매니저"),
                            ("LC", "러닝코치"),
                        ],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
