# Generated by Django 5.2.1 on 2025-06-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_birthday_user_self_introduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("MALE", "남성"), ("FEMALE", "여성")], default="MALE", max_length=6),
        ),
    ]
