# Generated by Django 5.2.1 on 2025-06-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_permissionsstaff_permissionsstudent_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="studentenrollmentrequest",
            table="student_enrollment_requests",
        ),
    ]
