# Generated by Django 5.2.3 on 2025-06-26 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models.withdrawals


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_studentenrollmentrequest_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[("TOO_EXPENSIVE", "비쌈"), ("NOT_SATISFIED", "불만족"), ("ETC", "기타")], max_length=20
                    ),
                ),
                ("reason_detail", models.TextField()),
                ("due_date", models.DateField(default=apps.users.models.withdrawals.two_weeks_later)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
    ]
