# Generated by Django 5.2.1 on 2025-06-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_socialuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="withdrawal", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
