# Generated by Django 5.2.1 on 2025-07-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_phoneverificationcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phoneverificationcode",
            name="user",
        ),
        migrations.AddField(
            model_name="phoneverificationcode",
            name="phone_number",
            field=models.CharField(default="000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="code",
            field=models.CharField(help_text="인증 코드", max_length=6),
        ),
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="expires_at",
            field=models.DateTimeField(help_text="만료 시간"),
        ),
    ]
