# Generated by Django 5.2.1 on 2025-06-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("thumbnail_img_url", models.CharField(default="default_img_url", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.subject")),
            ],
            options={
                "db_table": "test",
            },
        ),
        migrations.CreateModel(
            name="TestDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("duration_time", models.PositiveSmallIntegerField(default=60)),
                ("access_code", models.CharField(max_length=64)),
                ("open_at", models.DateTimeField()),
                ("close_at", models.DateTimeField()),
                ("questions_snapshot_json", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Activated", "활성화"), ("Deactivated", "비활성화")],
                        default="Activated",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.generation")),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tests.test")),
            ],
            options={
                "db_table": "test_deployment",
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("blank_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("options_json", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "객관식"),
                            ("ox", "O,X 퀴즈"),
                            ("ordering", "순서 정렬"),
                            ("fill_in_blank", "빈칸 채우기"),
                        ],
                        max_length=50,
                    ),
                ),
                ("answer", models.JSONField()),
                ("point", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tests.test")),
            ],
            options={
                "db_table": "test_question",
            },
        ),
        migrations.CreateModel(
            name="TestSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField()),
                ("cheating_count", models.PositiveSmallIntegerField(default=0)),
                ("answers_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tests.testdeployment"),
                ),
            ],
            options={
                "db_table": "test_submissions",
            },
        ),
    ]
