# Generated by Django 5.2.1 on 2025-06-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
        ("users", "0007_socialuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsubmission",
            name="student",
            field=models.ForeignKey(
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_submissions",
                to="users.permissionsstudent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("multiple_choice_single", "객관식 단일 선택"),
                    ("multiple_choice_multi", "객관식 다중 선택"),
                    ("ox", "O,X 퀴즈"),
                    ("ordering", "순서 정렬"),
                    ("fill_in_blank", "빈칸 채우기"),
                    ("short_answer", "주관식 단답형"),
                ],
                max_length=50,
            ),
        ),
    ]
