# Generated by Django 5.2.1 on 2025-07-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_testsubmission_student_alter_testquestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdeployment",
            name="test",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deployments", to="tests.test"
            ),
        ),
    ]
