# Generated by Django 5.2.1 on 2025-07-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_testsubmission_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdeployment",
            name="question_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testsubmission",
            name="correct_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
