# Generated by Django 5.2.1 on 2025-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
