# Generated by Django 5.2.1 on 2025-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_post_comment_count_post_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=500),
        ),
    ]
