# Generated by Django 5.2.1 on 2025-07-03 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_comment_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="img_url",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="postattachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_name",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_url",
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
